### ISSUE TITLE
Inconsistency with the dataset.

### ISSUE THREAD

**Issue by ashwani-bhat** [matalvepu/HKT#5]
Hi.

I have found some inconsistency in your dataset compared to original urfunny (version2) dataset.  I have added a screenshot below which shows that your dataset has less number of samples as compared to original urfunny dataset. 

![image](https://user-images.githubusercontent.com/16431244/128622798-48a9478f-36d9-4c8a-86ca-85c5b38e95b9.png)
Also you have mentioned in your paper that you have used version 2 of the urfunny dataset.
![image](https://user-images.githubusercontent.com/16431244/128623080-4ae59ee9-bab1-42a5-b03a-978b867ede82.png)

Can you kindly clear my doubt regarding this issue? Thanks

**Comment by matalvepu** [comment]
There were some noisy samples. Now everything is consistent.  Please download the UR-FUNNY-V2 again. Thanks for pointing it out.

**Comment by ashwani-bhat** [comment]
@matalvepu should I download your updated urfunny v2 dataset from here:[https://www.dropbox.com/s/5y8q52vj3jklwmm/ur_funny.pkl?dl=1]( https://www.dropbox.com/s/5y8q52vj3jklwmm/ur_funny.pkl?dl=1) or is their any other link to that?
Thanks.

**Comment by matalvepu** [comment]
Same link.

**Comment by ashwani-bhat** [comment]
@matalvepu I tried downloading ur_funny.pkl from the same link but its the same file as before (with inconsistency). Can you please provide the link here to your updated urfunny dataset? Thanks.
![urfunny_hkt](https://user-images.githubusercontent.com/16431244/128830893-648e18ed-6631-422a-a826-261cfbb0ecc7.png)
